apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu:22.04
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
  
  # kubectl exec -it ubuntu-test -- /bin/bash 
  # apt update && apt install vim-tiny