kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: wordslab-notebook-jupyterlab
  labels:
    app.kubernetes.io/name: jupyterlab
    app.kubernetes.io/instance: wordslab-notebook
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wordslab-notebook-jupyterlab
  labels:
    app.kubernetes.io/name: jupyterlab
    app.kubernetes.io/instance: wordslab-notebook
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/notebook`)
    kind: Rule
    services:
    - name: wordslab-notebook-jupyterlab
      port: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wordslab-notebook-jupyterlab
  labels:
    app.kubernetes.io/name: jupyterlab
    app.kubernetes.io/instance: wordslab-notebook
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jupyterlab
    app.kubernetes.io/instance: wordslab-notebook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordslab-notebook-jupyterlab
  labels:
    app.kubernetes.io/name: jupyterlab
    app.kubernetes.io/instance: wordslab-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyterlab
      app.kubernetes.io/instance: wordslab-notebook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jupyterlab
        app.kubernetes.io/instance: wordslab-notebook
    spec:
      containers:
        - name: jupyterlab
          image: "jupyter/minimal-notebook:python-3.10.8"
          imagePullPolicy: IfNotPresent
          workingDir: /home/wordslab/notebooks
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: NVIDIA_REQUIRE_CUDA
              value: "cuda>=11.7"
            - name: RESTARTABLE
              value: "yes"
            - name: DOCKER_STACKS_JUPYTER_CMD
              value: "lab"
            - name: NOTEBOOK_ARGS
              value: "--ServerApp.base_url=/notebooks --IdentityProvider.token=''"
            # To enable updating the image: https://github.com/kubernetes/kubernetes/issues/33664
            - name: RELEASE_DATE
              value: "12/16/2022"
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /notebooks
              port: http
            initialDelaySeconds: 15 
            failureThreshold: 40
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /notebooks
              port: http
            initialDelaySeconds: 15 
            failureThreshold: 40
            periodSeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /home/wordslab/notebooks
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data
          persistentVolumeClaim:
            claimName: wordslab-notebook-jupyterlab