name: Build and Publish lambda-stack-server Image

on:
  push:
    tags:
      - 'lambda-stack-server_v*'

env:
  IMAGE_NAME: lambda-stack-server

jobs:

  variables: 
    outputs:
      tag_name: ${{ steps.var.outputs.tag_name}}
    runs-on: ubuntu-latest
    steps:
      - name: Extracting tag name
        uses: actions/github-script@v6
        id: var
        with:
          script: |
            core.setOutput('tag_name', '${{ github.ref_name }}'.replace(/lambda-stack-server_v/, ''));

  build-and-publish:
    needs: variables
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ needs.variables.outputs.tag_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./wordslab.manager/images/lambda-stack
        file: lambda-stack-server.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}

    - name: Clean up Docker images
      run: docker image prune -f